config/routes.rb
Rails.application.routes.draw do

  

  root 'welcome#index'

  resources :welcome, only: [:index]
  resources :users
  resources :workouts
  resources :workout_programs, only: [:index, :show, :create]
  resources :workout_sessions
  resources :exercises, only: [:index, :show]
  resources :exercise_activities

  resources :muscles, only: [:index]
  resources :categories, only: [:index]

  get  "/login"  => 'sessions#new'
  post "/login"  => 'sessions#create'
  get  "/logout" => 'sessions#destroy'

  get "/summary" => 'users#summary'

end

app/models/daily_workout.rb
class DailyWorkout < ActiveRecord::Base
  belongs_to :workout_program

  has_many :exercise_recommendations
  has_many :exercises, through: :exercise_recommendations

  has_many :exercise_activities, through: :exercise_recommendations
  has_many :workout_sessions, through: :exercise_activities
  has_many :participants, through: :workout_sessions
end

app/models/exercise.rb
class Exercise < ActiveRecord::Base
  has_many :exercise_activities
  has_many :workout_sessions, through: :exercise_activities
  has_many :participants, through: :workout_sessions

  has_many :exercise_recommendations
  has_many :daily_workouts, through: :exercise_recommendations
  has_many :workout_programs, through: :daily_workouts

  belongs_to :muscle
end

app/models/exercise_activity.rb
class ExerciseActivity < ActiveRecord::Base
  belongs_to :workout_session
  belongs_to :exercise
  belongs_to :exercise_recommendation

end

app/models/exercise_recommendation.rb
class ExerciseRecommendation < ActiveRecord::Base
  belongs_to :daily_workout
  belongs_to :exercise
end

app/models/gallery.rb
class Gallery < ActiveRecord::Base
  belongs_to :owner, class_name: "User"
end

app/models/meetup.rb
class Meetup < ActiveRecord::Base
  has_many :workout_sessions
  has_many :participants, through: :workout_sessions
end

app/models/muscle.rb
class Muscle < ActiveRecord::Base
  has_many :exercises
  belongs_to :muscle_group

  # def self.muscle_groups
  # 	self.all.map do |muscle|
  # 		muscle.muscle_group
  # 	end.uniq
  # end
end

app/models/muscle_group.rb
class MuscleGroup < ActiveRecord::Base
  has_many :muscles
  has_many :exercises, through: :muscles
end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
  belongs_to :first_friend, class_name: "User"
  belongs_to :second_friend, class_name: "User"
end

app/models/user.rb
class User < ActiveRecord::Base
  # need to look into this more
  # has_many :relationships
  has_many :galleries, foreign_key: :owner_id
  has_many :weight_goals, foreign_key: :participant_id

  has_many :workout_sessions, foreign_key: :participant_id
  has_many :meetups, through: :workout_sessions

  has_many :exercise_activities, through: :workout_sessions
  has_many :exercises, through: :exercise_activities

  has_many :exercise_recommendations, through: :exercise_activities
  has_many :daily_workouts, through: :exercise_recommendations
  
  has_many :user_workout_programs
  has_many :workout_programs, through: :user_workout_programs



  # validates :name, :length => { :minimum => 1, :message => "must be at least 3 characters!" }
  validates :password, :length => { :minimum => 6 }
  validates :email, :uniqueness => true, :format => /.+@.+\..+/

  def password
      @password ||= BCrypt::Password.new(password_hash)
  end

  def password=(new_password)
      @password = BCrypt::Password.create(new_password)
      self.password_hash = @password
  end

  def self.authenticate(email, password)
   user = User.find_by_email(email)
    return user if user && (user.password == password)
  end
end

app/models/user_workout_program.rb
class UserWorkoutProgram < ActiveRecord::Base
  belongs_to :user
  belongs_to :workout_program
end

app/models/weight_goal.rb
class WeightGoal < ActiveRecord::Base
  belongs_to :participant, class_name: "User"
end

app/models/workout_program.rb
class WorkoutProgram < ActiveRecord::Base
  has_many :daily_workouts
  has_many :exercises_recommendations, through: :daily_workouts

  has_many :exercises, through: :exercises_recommendations

  has_many :exercise_activities, through: :exercises_recommendations
  has_many :workout_sessions, through: :exercise_activities
  
  has_many :user_workout_programs
  has_many :users, through: :user_workout_programs
end

app/models/workout_session.rb
class WorkoutSession < ActiveRecord::Base
  belongs_to :meetup
  belongs_to :participant, class_name: "User"

  has_many :exercise_activities

  has_many :exercises, through: :exercise_activities

  has_many :exercise_recommendations, through: :exercise_activities
  has_many :daily_workouts, through: :exercise_recommendations
  has_many :workout_programs, through: :daily_workouts
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @exercises = Exercise.all
    @muscles = Muscle.order(:name)
    @categories = MuscleGroup.all
    
    if logged_in?
      render :index, layout: false
    else
      redirect_to root_path
    end
  end
end

app/controllers/exercises_controller.rb
class ExercisesController < ApplicationController
  def index
    @exercises = Exercise.all
    @muscles = Muscle.order(:name)

    if logged_in?
      render :index
    else
      redirect_to root_path
    end
  end

  def show
    @exercise = Exercise.find(params[:id])
  end
end

app/controllers/muscles_controller.rb
class MusclesController < ApplicationController
  def index
    @exercises = Exercise.all
    @muscles = Muscle.order(:name)

    if logged_in?
      render :index, layout: false
    else
      redirect_to root_path
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: session_params[:email])
    if user && user.password == session_params[:password]
      session[:user_id] = user.id
      flash[:notice] = "Signed in as #{user.email}."
      # redirect_to workouts_path
      redirect_to summary_path      
    else
      @email = session_params[:email]
      flash[:alert] = "Email/password combination not valid."
      render :new
    end
  end

  def destroy
    session.delete(:user_id)
    flash[:notice] = "Successfully logged out."
    redirect_to root_path
  end


  private
  def session_params
    params.require(:session).permit(:username, :password, :email)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      redirect_to workouts_path
    else
      @errors = @user.errors
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def summary
    if logged_in?
      render :summary
    else
      redirect_to login_path
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :password, :email, :first_name, :last_name, :image_url)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/controllers/workouts_controller.rb
class WorkoutsController < ApplicationController
  def index
    if logged_in?
      render :index
    else
      redirect_to root_path
    end
  end

  def new
  end

  def create
    @current_workout = WorkoutSession.create!({participant_id: current_user.id})
    redirect_to workout_session_path(@current_workout.id)
  end

  def show

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def current_user
		@_user ||= User.find_by(id: session[:user_id])
	end
end

app/views/muscles/index.html.erb
<% @muscles.each do |muscle| %>

  <div class="muscle-category-items"><button class="btn btn-default muscle-btn btn-block"><%= image_tag muscle.muscle_thumbnail %> <%= muscle.name %></button></div>
  <div class="muscle-workout-list" style="display: none">
  <p> Top <%= muscle.name.capitalize %> Workouts </p>
    <ul>
      <% muscle.exercises.each do |exercise| %>
        <li><%= link_to exercise.name, exercise_path(exercise.id) %></li>
        <% if session[:workout_session_id] %>
					<%= button_to "Add to Workout", "#", class: "add-to-workout-btn", id: exercise.id %>
        <% end %>
      <% end %>
    </ul>
    </div>
<% end %>

app/views/users/new.html.erb
<h1>Sign Up</h1>
		<%= form_for(@user) do |f| %>
			<%= f.label :username %>
			<%= f.text_field :username, class: 'form-control' %>

		  <%= f.label :first_name %>
		  <%= f.text_field :first_name, class: 'form-control' %>

		  <%= f.label :last_name %>
		  <%= f.text_field :last_name, class: 'form-control' %>

		  <%= f.label :email %>
		  <%= f.text_field :email, class: 'form-control' %>

		  <%= f.label :password %>
		  <%= f.password_field :password, class: 'form-control' %>

		  <%= f.label :image_url %>
		  <%= f.text_field :image_url, class: 'form-control' %>

		  <%= f.submit  "Create Account", class: "btn btn-primary" %>
		<% end %>
	</div>
</div>

app/views/users/summary.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-2">
      <ul class="nav nav-pills nav-stacked admin-menu">
        <li class="active"><a href="#" data-target-id="home">Home</a></li>
        <li><%= link_to "Workout Session", "#" %></li>
        <li><%= link_to "Workout Progress", "#" %></li>
        <li><%= link_to "Settings", "#" %></li>
        <li><%= link_to "Most Used Exercises...", "#" %></li>
      </ul>
    </div>
    <div class="col-md-10">
      <div class="row">
        <div class="col-md-8 well admin-content" id="home">
          <h3 class="page-header"><%= current_user.first_name.capitalize%></h3>
          <div class="row">
            <div class="col-xs-6">
              <% if current_user.image_url? %>
                <img src=<%= current_user.image_url %> class="img-thumbnail" width="304" height="236">
              <% else %>
                <img src="http://www.ie.uic.edu/iie/empty-person-image.jpg" class="img-thumbnail" width="304" height="236">
              <% end %>
            </div>
            <div class="col-xs-6">
              <table class="center">
                <tbody>
                  <tr>
                    <td> <%= current_user.first_name.capitalize %> <%= current_user.last_name.capitalize %> </td>
                  </tr>
                  <tr>
                    <td>Email: <%= current_user.email %></td>
                  </tr>
                </tbody>
              </table>
            </div>
          </div>
        </div>
        <div class="col-md-4">
          <div class="panel panel-default">
            <div class="panel-heading">
              <i class="fa fa-bell fa-fw"></i> Notifications Panel
            </div>
            <div class="panel-body">
              <div class="list-group">
                <%# @question = current_user.questions.order("questions.created_at desc limit(5)") %>
                <%# @question.each do |question| %>
                <a href="<%#= question_path(question.id) %>" class="list-group-item">
                  <i class="fa fa-comment fa-fw"></i> New Question Posted
                  <span class="pull-right text-muted small"><em><%#= question_activity(question.id) %> </em>
                  </span>
                </a>
                <%# end %>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-md-3">
          <div class="panel panel-blue">
            <div class="panel-heading">
              <div class="row">
                <div class="col-xs-3">
                  <i class="fa fa-comments fa-5x"></i>
                </div>
                <div class="col-xs-9 text-right">
                  <div class="huge"><%#= current_user.questions.count %></div>
                  <div>Questions</div>
                </div>
              </div>
            </div>
            <a href="#">
              <div class="panel-footer">
                <span class="pull-left">View Details</span>
                <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                <div class="clearfix"></div>
              </div>
            </a>
          </div>
        </div>
        <div class="col-md-3">
          <div class="panel panel-green">
            <div class="panel-heading">
              <div class="row">
                <div class="col-xs-3">
                  <i class="fa fa-check-circle fa-5x"></i>
                </div>
                <div class="col-xs-9 text-right">
                  <div class="huge"><%#= current_user.answers.count %></div>
                  <div>Answers</div>
                </div>
              </div>
            </div>
            <a href="#">
              <div class="panel-footer">
                <span class="pull-left">View Details</span>
                <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                <div class="clearfix"></div>
              </div>
            </a>
          </div>
        </div>
        <div class="col-md-3">
          <div class="panel panel-yellow">
            <div class="panel-heading">
              <div class="row">
                <div class="col-xs-3">
                  <i class="fa fa-star fa-5x"></i>
                </div>
                <div class="col-xs-9 text-right">
                    <div class="huge"><%#= current_user.total_votes %></div>
                  <div>Votes Received</div>
                </div>
              </div>
            </div>
            <a href="#">
              <div class="panel-footer">
                <span class="pull-left">View Details</span>
                <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                <div class="clearfix"></div>
              </div>
            </a>
          </div>
        </div>
        <div class="col-md-3">
          <div class="panel panel-gray">
            <div class="panel-heading">
              <div class="row">
                <div class="col-xs-3">
                  <i class="fa fa-thumbs-o-up fa-5x"></i>
                </div>
                <div class="col-xs-9 text-right">
                  <div class="huge"><%#= current_user.cast_votes.count %></div>
                  <div>Votes Cast</div>
                </div>
              </div>
            </div>
            <a href="#">
              <div class="panel-footer">
                <span class="pull-left">View Details</span>
                <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                <div class="clearfix"></div>
              </div>
            </a>
          </div>
        </div>
      </div>
    </div>
  </div>