config/routes.rb
Rails.application.routes.draw do

  

  root 'welcome#index'

  resources :welcome, only: [:index]
  resources :users
  resources :workouts
  resources :workout_programs, only: [:index, :show, :create]
  resources :workout_sessions
  resources :exercises, only: [:index, :show]
  resources :exercise_activities

  resources :muscles, only: [:index]
  resources :categories, only: [:index]

  get  "/login"  => 'sessions#new'
  post "/login"  => 'sessions#create'
  get  "/logout" => 'sessions#destroy'

  get "/summary" => 'users#summary'

end

app/models/daily_workout.rb
class DailyWorkout < ActiveRecord::Base
  belongs_to :workout_program

  has_many :exercise_recommendations
  has_many :exercises, through: :exercise_recommendations

  has_many :exercise_activities, through: :exercise_recommendations
  has_many :workout_sessions, through: :exercise_activities
  has_many :participants, through: :workout_sessions
end

app/models/exercise.rb
class Exercise < ActiveRecord::Base
  has_many :exercise_activities
  has_many :workout_sessions, through: :exercise_activities
  has_many :participants, through: :workout_sessions

  has_many :exercise_recommendations
  has_many :daily_workouts, through: :exercise_recommendations
  has_many :workout_programs, through: :daily_workouts

  belongs_to :muscle
end

app/models/exercise_activity.rb
class ExerciseActivity < ActiveRecord::Base
  belongs_to :workout_session
  belongs_to :exercise
  belongs_to :exercise_recommendation

end

app/models/exercise_recommendation.rb
class ExerciseRecommendation < ActiveRecord::Base
  belongs_to :daily_workout
  belongs_to :exercise
end

app/models/gallery.rb
class Gallery < ActiveRecord::Base
  belongs_to :owner, class_name: "User"
end

app/models/meetup.rb
class Meetup < ActiveRecord::Base
  has_many :workout_sessions
  has_many :participants, through: :workout_sessions
end

app/models/muscle.rb
class Muscle < ActiveRecord::Base
  has_many :exercises
  belongs_to :muscle_group

  # def self.muscle_groups
  # 	self.all.map do |muscle|
  # 		muscle.muscle_group
  # 	end.uniq
  # end
end

app/models/muscle_group.rb
class MuscleGroup < ActiveRecord::Base
  has_many :muscles
  has_many :exercises, through: :muscles
end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
  belongs_to :first_friend, class_name: "User"
  belongs_to :second_friend, class_name: "User"
end

app/models/user.rb
class User < ActiveRecord::Base
  # need to look into this more
  # has_many :relationships
  has_many :galleries, foreign_key: :owner_id
  has_many :weight_goals, foreign_key: :participant_id

  has_many :workout_sessions, foreign_key: :participant_id
  has_many :meetups, through: :workout_sessions

  has_many :exercise_activities, through: :workout_sessions
  has_many :exercises, through: :exercise_activities

  has_many :exercise_recommendations, through: :exercise_activities
  has_many :daily_workouts, through: :exercise_recommendations
  
  has_many :user_workout_programs
  has_many :workout_programs, through: :user_workout_programs



  # validates :name, :length => { :minimum => 1, :message => "must be at least 3 characters!" }
  validates :password, :length => { :minimum => 6 }
  validates :email, :uniqueness => true, :format => /.+@.+\..+/

  def password
      @password ||= BCrypt::Password.new(password_hash)
  end

  def password=(new_password)
      @password = BCrypt::Password.create(new_password)
      self.password_hash = @password
  end

  def self.authenticate(email, password)
   user = User.find_by_email(email)
    return user if user && (user.password == password)
  end
end

app/models/user_workout_program.rb
class UserWorkoutProgram < ActiveRecord::Base
  belongs_to :user
  belongs_to :workout_program
end

app/models/weight_goal.rb
class WeightGoal < ActiveRecord::Base
  belongs_to :participant, class_name: "User"
end

app/models/workout_program.rb
class WorkoutProgram < ActiveRecord::Base
  has_many :daily_workouts
  has_many :exercises_recommendations, through: :daily_workouts

  has_many :exercises, through: :exercises_recommendations

  has_many :exercise_activities, through: :exercises_recommendations
  has_many :workout_sessions, through: :exercise_activities
  
  has_many :user_workout_programs
  has_many :users, through: :user_workout_programs
end

app/models/workout_session.rb
class WorkoutSession < ActiveRecord::Base
  belongs_to :meetup
  belongs_to :participant, class_name: "User"

  has_many :exercise_activities

  has_many :exercises, through: :exercise_activities

  has_many :exercise_recommendations, through: :exercise_activities
  has_many :daily_workouts, through: :exercise_recommendations
  has_many :workout_programs, through: :daily_workouts
end

app/controllers/exercises_controller.rb
class ExercisesController < ApplicationController
  def index
    @exercises = Exercise.all
    @muscles = Muscle.order(:name)

    if logged_in?
      render :index
    else
      redirect_to root_path
    end
  end

  def show
    @exercise = Exercise.find(params[:id])
  end
end

app/controllers/muscles_controller.rb
class MusclesController < ApplicationController
  def index
    @exercises = Exercise.all
    @muscles = Muscle.order(:name)

    if logged_in?
      render :index, layout: false
    else
      redirect_to root_path
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: session_params[:email])
    if user && user.password == session_params[:password]
      session[:user_id] = user.id
      flash[:notice] = "Signed in as #{user.email}."
      # redirect_to workouts_path
      redirect_to summary_path      
    else
      @email = session_params[:email]
      flash[:alert] = "Email/password combination not valid."
      render :new
    end
  end

  def destroy
    session.delete(:user_id)
    flash[:notice] = "Successfully logged out."
    redirect_to root_path
  end


  private
  def session_params
    params.require(:session).permit(:username, :password, :email)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      redirect_to workouts_path
    else
      @errors = @user.errors
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def summary
    if logged_in?
      render :summary
    else
      redirect_to login_path
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :password, :email, :first_name, :last_name, :image_url)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/controllers/workouts_controller.rb
class WorkoutsController < ApplicationController
  def index
    if logged_in?
      render :index
    else
      redirect_to root_path
    end
  end

  def new
  end

  def create
    @current_workout = WorkoutSession.create!({participant_id: current_user.id})
    redirect_to workout_session_path(@current_workout.id)
  end

  def show

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def current_user
		@_user ||= User.find_by(id: session[:user_id])
	end
end

app/views/exercises/index.html.erb
<div class="button-menu">
	<%= link_to "View By Muscles", muscles_path, class: "browse-exercise-btn btn-lg btn-primary btn-block" %>
	<%= link_to "View By Category", categories_path, class: "browse-exercise-btn btn-lg btn-primary btn-block" %>
</div>
    

<div class="exercise-group" style="display: none"></div>

app/views/exercises/show.html.erb
<h1><%= @exercise.name %></h1>

<div class="exercise-info">

<div class="exercise-equipment"> <h3>Equipment: </h3> <%= @exercise.equipment %> </div>
<div class="primiary-muscle"><h3>Primary Muscle: </h3> <%= @exercise.muscle.name %></div>
<div class="exercise-description"><p><%= @exercise.description %></p></div>
<div class="muscle-image"><%= image_tag @exercise.image %></div>

</div>

app/views/welcome/index.html.erb
    <!-- Image Background Page Header -->
    <!-- Note: The background image is set within the business-casual.css file. -->
    <header class="business-header">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <h1 class="tagline">Your Fitness</h1>
                </div>
            </div>
        </div>
    </header>

    <!-- Page Content -->
    <div class="container">

        <hr>

        <div class="row">
         <div class="col-sm-4">
             <%= image_tag "girl_app_gym.jpg", class: "img-circle img-responsive img-center", alt: "" %>
            <h2>Log Your Workouts With Ease</h2>
            <p>Get started with a workout plan, browse exercises by muscle or by category and start lifting. Simple interface allows you log your results quickly so you can move on to your next set.</p>
        </div>
        <div class="col-sm-4">
            <%= image_tag "gym-buddies.jpg", class: "img-circle img-responsive img-center", alt: "" %>
            <h2>Find a Spotter</h2>
            <p>Need a workout buddy? Fitness Tracker lets you find or set up times to meet up with other fitness enthusiasts in your area.</p>
        </div>
        <div class="col-sm-4">
            <%= image_tag "share_gym.jpg", class: "img-circle img-responsive img-center", alt: "" %>
            <h2>Keep Track and Share your Progress</h2>
            <p>Your summary page allows you to keep track of all of the highlights for your workout and share your big accomplishments and goals with friends on Facebook and Google+</p>
        </div>

    </div>
        <!-- /.row -->

        <hr>

        <div class="row">
            <div class="col-sm-12">
                <h2>Get Started Today</h2>
                <p>
                  <%= link_to "Sign Up Now", new_user_path, class: "btn btn-default btn-lg" %>
                </p>
            </div>
        </div>
        <!-- /.row -->

        <hr>

        <!-- Footer -->
        <footer>
            <div class="row">
                <div class="col-lg-12">
                    <p>Footer Here</p>
                </div>
            </div>
            <!-- /.row -->
        </footer>

    </div>
    <!-- /.container -->

app/views/workouts/index.html.erb
<%= button_to "New Workout Session", workout_sessions_path, method: "post" %>

<% if current_user.workout_programs.count >= 1 %>
<%= button_to "Continue Workout Program", workout_programs_path, :method => "get" %>
<% end %>
<%= button_to "Start New Workout Program", workout_programs_path, :method => "get" %>

app/views/workouts/new.html.erb
<!-- do not use this right now -->