config/routes.rb
Rails.application.routes.draw do

  

  root 'welcome#index'

  resources :welcome, only: [:index]
  resources :users
  resources :workouts
  resources :workout_programs, only: [:index, :show, :create]
  resources :workout_sessions
  resources :exercises, only: [:index, :show]
  resources :exercise_activities

  resources :muscles, only: [:index]
  resources :categories, only: [:index]

  get  "/login"  => 'sessions#new'
  post "/login"  => 'sessions#create'
  get  "/logout" => 'sessions#destroy'

  get "/summary" => 'users#summary'

end

app/models/daily_workout.rb
class DailyWorkout < ActiveRecord::Base
  belongs_to :workout_program

  has_many :exercise_recommendations
  has_many :exercises, through: :exercise_recommendations

  has_many :exercise_activities, through: :exercise_recommendations
  has_many :workout_sessions, through: :exercise_activities
  has_many :participants, through: :workout_sessions
end

app/models/exercise.rb
class Exercise < ActiveRecord::Base
  has_many :exercise_activities
  has_many :workout_sessions, through: :exercise_activities
  has_many :participants, through: :workout_sessions

  has_many :exercise_recommendations
  has_many :daily_workouts, through: :exercise_recommendations
  has_many :workout_programs, through: :daily_workouts

  belongs_to :muscle
end

app/models/exercise_activity.rb
class ExerciseActivity < ActiveRecord::Base
  belongs_to :workout_session
  belongs_to :exercise
  belongs_to :exercise_recommendation

end

app/models/exercise_recommendation.rb
class ExerciseRecommendation < ActiveRecord::Base
  belongs_to :daily_workout
  belongs_to :exercise
end

app/models/gallery.rb
class Gallery < ActiveRecord::Base
  belongs_to :owner, class_name: "User"
end

app/models/meetup.rb
class Meetup < ActiveRecord::Base
  has_many :workout_sessions
  has_many :participants, through: :workout_sessions
end

app/models/muscle.rb
class Muscle < ActiveRecord::Base
  has_many :exercises
  belongs_to :muscle_group

  # def self.muscle_groups
  # 	self.all.map do |muscle|
  # 		muscle.muscle_group
  # 	end.uniq
  # end
end

app/models/muscle_group.rb
class MuscleGroup < ActiveRecord::Base
  has_many :muscles
  has_many :exercises, through: :muscles
end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
  belongs_to :first_friend, class_name: "User"
  belongs_to :second_friend, class_name: "User"
end

app/models/user.rb
class User < ActiveRecord::Base
  # need to look into this more
  # has_many :relationships
  has_many :galleries, foreign_key: :owner_id
  has_many :weight_goals, foreign_key: :participant_id

  has_many :workout_sessions, foreign_key: :participant_id
  has_many :meetups, through: :workout_sessions

  has_many :exercise_activities, through: :workout_sessions
  has_many :exercises, through: :exercise_activities

  has_many :exercise_recommendations, through: :exercise_activities
  has_many :daily_workouts, through: :exercise_recommendations
  
  has_many :user_workout_programs
  has_many :workout_programs, through: :user_workout_programs



  # validates :name, :length => { :minimum => 1, :message => "must be at least 3 characters!" }
  validates :password, :length => { :minimum => 6 }
  validates :email, :uniqueness => true, :format => /.+@.+\..+/

  def password
      @password ||= BCrypt::Password.new(password_hash)
  end

  def password=(new_password)
      @password = BCrypt::Password.create(new_password)
      self.password_hash = @password
  end

  def self.authenticate(email, password)
   user = User.find_by_email(email)
    return user if user && (user.password == password)
  end
end

app/models/user_workout_program.rb
class UserWorkoutProgram < ActiveRecord::Base
  belongs_to :user
  belongs_to :workout_program
end

app/models/weight_goal.rb
class WeightGoal < ActiveRecord::Base
  belongs_to :participant, class_name: "User"
end

app/models/workout_program.rb
class WorkoutProgram < ActiveRecord::Base
  has_many :daily_workouts
  has_many :exercises_recommendations, through: :daily_workouts

  has_many :exercises, through: :exercises_recommendations

  has_many :exercise_activities, through: :exercises_recommendations
  has_many :workout_sessions, through: :exercise_activities
  
  has_many :user_workout_programs
  has_many :users, through: :user_workout_programs
end

app/models/workout_session.rb
class WorkoutSession < ActiveRecord::Base
  belongs_to :meetup
  belongs_to :participant, class_name: "User"

  has_many :exercise_activities

  has_many :exercises, through: :exercise_activities

  has_many :exercise_recommendations, through: :exercise_activities
  has_many :daily_workouts, through: :exercise_recommendations
  has_many :workout_programs, through: :daily_workouts
end

app/controllers/muscles_controller.rb
class MusclesController < ApplicationController
  def index
    @exercises = Exercise.all
    @muscles = Muscle.order(:name)

    if logged_in?
      render :index, layout: false
    else
      redirect_to root_path
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: session_params[:email])
    if user && user.password == session_params[:password]
      session[:user_id] = user.id
      flash[:notice] = "Signed in as #{user.email}."
      # redirect_to workouts_path
      redirect_to summary_path      
    else
      @email = session_params[:email]
      flash[:alert] = "Email/password combination not valid."
      render :new
    end
  end

  def destroy
    session.delete(:user_id)
    flash[:notice] = "Successfully logged out."
    redirect_to root_path
  end


  private
  def session_params
    params.require(:session).permit(:username, :password, :email)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      redirect_to workouts_path
    else
      @errors = @user.errors
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def summary
    if logged_in?
      render :summary
    else
      redirect_to login_path
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :password, :email, :first_name, :last_name, :image_url)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/controllers/workouts_controller.rb
class WorkoutsController < ApplicationController
  def index
    if logged_in?
      render :index
    else
      redirect_to root_path
    end
  end

  def new
  end

  def create
    @current_workout = WorkoutSession.create!({participant_id: current_user.id})
    redirect_to workout_session_path(@current_workout.id)
  end

  def show

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def current_user
		@_user ||= User.find_by(id: session[:user_id])
	end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Fitness Tracker</title>
	<%= stylesheet_link_tag    'application', media: 'all' %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	<%= csrf_meta_tags %>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
	<!-- Navigation -->
	<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
		<div class="container">
			<!-- Brand and toggle get grouped for better mobile display -->
			<div class="navbar-header">
				<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
					<span class="sr-only">Toggle navigation</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
				<%= link_to "Fitness Tracker", root_url, class: "navbar-brand" %>
			</div>
			<!-- Collect the nav links, forms, and other content for toggling -->
			<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
				<ul class="nav navbar-nav navbar-right">
					<% if current_user %>

					<li><%= link_to "My Summary", summary_path %></li>
					<li class="dropdown">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown">Exercises <b class="caret"></b></a>
						<ul class="dropdown-menu">
							<li>
								<%= link_to "Browse Exercises", exercises_path %>
							</li>
							<li>
								<%= link_to "Workout Programs", workout_programs_path %>
							</li>
							<li>
								<%= link_to "Start Daily Exercise", "#" %>
							</li>
						</ul>
					</li>
					<li><%= link_to "Workout Meetup", "#" %></li>
					<li><%= link_to "Log Out", logout_path %></li>

					<% else %>

					<li><%= link_to "Sign In", login_path %>
					<%end %>
				</ul>
			</div>
			<!-- /.navbar-collapse -->
		</div>
	</nav>  
	<%= yield %>
</body>
</html>